name: todo_mvc
version: 0.0.2
description: todo_mvc application that uses dartling for its model.
author: Your Name
homepage: http://ondart.me/
documentation:
dependencies:
  browser: any
  dartling:
    git: https://github.com/dzenanr/dartling.git

  