name: todo_mvc
version: 2.0.1
description: todo_mvc application that uses dartling for its model.
author: Dzenan Ridjanovic
homepage: http://ondart.me/
documentation:
dependencies:
  browser: any
  dartling: any


  