name: todo_mvc
version: 2.0.1
description: todo_mvc server on DartVoid that uses dartling for its model and MongoDB for its database.
author: Dzenan Ridjanovic
homepage: http://ondart.me/
documentation:
dependencies:
  dartling: any
  mongo_dart: any